development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:0fa2b1ec0a72aa0196ca093a3fb95358@barb.redistogo.com:9401/

  channel_prefix: message_me_production
